#!/bin/bash

tput sgr0

RED=$(tput setaf 1)
YELLOW=$(tput setaf 3)
GREEN=$(tput setaf 2)
PURPLE=$(tput setaf 5)
BLUE=$(tput setaf 4)
WHITE=$(tput setaf 7)
BOLD=$(tput bold)
RESET=$(tput sgr0)

LOG_STATUS_SUCCESS="✔"
LOG_STATUS_ERROR="✖"
LOG_STATUS_INFO="➜"

e_header()   {
  local MSG="$1"
  local COLOR="$2"

  [[ -z $COLOR ]] && COLOR="${BLUE}"
  [[ -n $__LOG_COLOR_HEADER ]] && COLOR="${__LOG_COLOR_HEADER}"

  SUPRESS_TIMESTAMP_BKP=${SUPRESS_TIMESTAMP}
  SUPRESS_TIMESTAMP=true

  e_line
  e_line "== ${MSG} ==" "${BOLD}${COLOR}" "" "${BOLD}${COLOR}"

  SUPRESS_TIMESTAMP=${SUPRESS_TIMESTAMP_BKP}
}

e_line() {
  local MSG="$1"
  local COLOR="$2"
  local STATUS="$3"
  local STATUS_COLOR="$4"
  local LINE_BREAK="$5"
  local TIMESTAMP="["$(date "+%d-%m-%Y %H:%M:%S")"]"

  [[ -n $__LOG_COLOR_LINE && -z "${COLOR}" ]] && COLOR="${__LOG_COLOR_LINE}"
  [[ -z $COLOR ]] && COLOR="${BLUE}"
  [[ -z $STATUS ]] && STATUS=" "
  [[ -z $STATUS_COLOR ]] && STATUS_COLOR=${PURPLE}
  [[ ${LINE_BREAK:-true} != false ]] && LINE_BREAK="\n" || LINE_BREAK=""
  [[ $SUPRESS_TIMESTAMP || -z $MSG ]] && TIMESTAMP=""

  printf "${STATUS_COLOR}${TIMESTAMP} %s${RESET} ${COLOR}%s${RESET}${LINE_BREAK}" "${STATUS}" "${MSG}"
}

e_success() {
  e_line "$1" "${GREEN}" "${LOG_STATUS_SUCCESS}" "${GREEN}"
}

e_error() {
  e_line "$1" "${RED}" "${LOG_STATUS_ERROR}" "${RED}"
}

e_info() {
  e_line "$1" "${WHITE}" "${LOG_STATUS_INFO}" "${BLUE}"
}

e_warning() {
  e_line "$1" "${YELLOW}" "${LOG_STATUS_INFO}" "${BOLD}${RED}"
}

e_inline() {
  e_line "$1" "$2" "$3" "$4" false
}

e_start_spinner() {
  E_SPINNER_START_MESSAGE=""
  [[ "$1" ]] && E_SPINNER_START_MESSAGE="$1"
  [[ "$2" ]] && E_SPINNER_END_MESSAGE="$2"
  [[ $E_SPINNER_START_MESSAGE ]] && e_inline "$E_SPINNER_START_MESSAGE" "${WHITE}" "${LOG_STATUS_INFO}" "${BLUE}"
  e_spinner &
  E_SPINNER_PID=$!
  disown $E_SPINNER_PID #make sure bash doesn't freak out when we kill the spinner
}

e_spinner() {
  local i sp n
  sp='/-\|'
  n=${#sp}
  while sleep 0.1; do
      local temp=${sp#?}
      printf " [%c]  " "$sp"
      local sp=$temp${sp%"$temp"}
      printf "\b\b\b\b\b\b"
  done
}

e_stop_spinner() {
  kill $E_SPINNER_PID &> /dev/null
  [[ $E_SPINNER_START_MESSAGE ]] && printf "    \b\b\b\b"
  [[ $E_SPINNER_END_MESSAGE ]] && e_reset_line && e_inline "$E_SPINNER_END_MESSAGE" "${WHITE}" "${LOG_STATUS_INFO}" "${BLUE}"
  printf "\n"
}

e_reset_line() {
  local COLS=$(tput cols)
  printf "\r" && printf "%${COLS}s\r"
}
