#!/usr/bin/env bash


setup_path() {
  DIR="${BASH_SOURCE%/*}"
  if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
}

setup_path
#list all utils you wish to load, in order
source "${DIR}/os"
source "${DIR}/log"

#load this script in your other scripts following the example below:
#
# DIR="${BASH_SOURCE%/*}"
# if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
# source "${DIR}/utils/utils"
