let s:root=expand('~/.dotfiles/config/vim')
if !empty(glob(s:root))
    let $VIMHOME=s:root
    let &runtimepath .= ','.$VIMHOME.','.$VIMHOME.'/after'
    call main#init()
endif
" Related Files ---------------------------------------- {{{
" config/vim/.vim/after/ftplugin/javascript_swapit.vim
" config/vim/.vim/after/ftplugin/sh_swapit.vim
" config/vim/.vim/after/plugin/UltiSnips.vim
" config/vim/.vim/after/plugin/UndoTree.vim
" config/vim/.vim/after/plugin/abolish.vim
" config/vim/.vim/after/plugin/ale.vim
" config/vim/.vim/after/plugin/auto-pairs.vim
" config/vim/.vim/after/plugin/autocmnds.vim
" config/vim/.vim/after/plugin/cm.vim
" config/vim/.vim/after/plugin/commentray.vim
" config/vim/.vim/after/plugin/easy_align.vim
" config/vim/.vim/after/plugin/editorconfig.vim
" config/vim/.vim/after/plugin/emmet.vim
" config/vim/.vim/after/plugin/fzf.vim
" config/vim/.vim/after/plugin/gista.vim
" config/vim/.vim/after/plugin/gitgutter.vim
" config/vim/.vim/after/plugin/grepper.vim
" config/vim/.vim/after/plugin/guttentags.vim
" config/vim/.vim/after/plugin/markdown.vim
" config/vim/.vim/after/plugin/matchup.vim
" config/vim/.vim/after/plugin/sandwich.vim
" config/vim/.vim/after/plugin/startify.vim
" config/vim/.vim/autoload/.gitignore
" config/vim/.vim/autoload/functions.vim
" config/vim/.vim/autoload/main.vim
" config/vim/.vim/autoload/packages.vim
" config/vim/.vim/autoload/plug.vim
" config/vim/.vim/autoload/statusline.vim
" config/vim/.vim/ftdetect/json.vim
" config/vim/.vim/ftdetect/markdown.vim
" config/vim/.vim/ftdetect/ruby.vim
" config/vim/.vim/ftdetect/tags.vim
" config/vim/.vim/ftdetect/zsh.vim
" config/vim/.vim/ftplugin/fzf.vim
" config/vim/.vim/ftplugin/gitcommit.vim
" config/vim/.vim/ftplugin/gitrebase.vim
" config/vim/.vim/ftplugin/handlebars.vim
" config/vim/.vim/ftplugin/markdown.vim
" config/vim/.vim/ftplugin/php.vim
" config/vim/.vim/ftplugin/twig.vim
" config/vim/.vim/ftplugin/vim.vim
" config/vim/.vim/plugin/README.md
" config/vim/.vim/plugin/autocmnds.vim
" config/vim/.vim/plugin/color.vim
" config/vim/.vim/plugin/commands.vim
" config/vim/.vim/plugin/indent-line.vim
" config/vim/.vim/plugin/mappings.vim
" config/vim/.vim/plugin/settings.vim
" config/vim/.vim/plugin/statusline.vim
" config/vim/.vim/spell/en.utf-8.add
" config/vim/.vim/spell/en.utf-8.spl
" config/vim/.vim/spell/en.utf-8.sug
" config/vim/.vim/spell/pt.utf-8.spl
" config/vim/.vim/ultisnips/all.snippets
" config/vim/.vim/ultisnips/javascript.snippets
" config/vim/.vim/ultisnips/php.snippets
" config/vim/.vim/ultisnips/snippets.snippets
" config/vim/.vim/ultisnips/twig.snippets
" }}} ---------------------------------------- /Related Files
