session_name: Saraiva
windows:
- focus: 'true'
  layout: 8f0a,318x82,0,0[318x66,0,0,1,318x15,0,67{73x15,0,67,2,166x15,74,67,3,77x15,241,67,4}]
  options:
    automatic-rename: 'off'
  panes:
  - focus: 'true'
    shell_command:
    - cd /Users/filipekiss/work/saraiva-magento
  - shell_command:
    - cd /Users/filipekiss/work/saraiva-magento/gulp
  - shell_command:
    - cd /Users/filipekiss/work/saraiva-magento
    - git status
  - shell_command:
    - cd /Users/filipekiss/work/saraiva-docker
    - ctop -a
  window_name: Saraiva
