session_name: Saraiva
windows:
- focus: 'true'
  layout: bf00,318x82,0,0,3
  options:
    automatic-rename: 'off'
    remain-on-exit: 'off'
    synchronize-panes: 'off'
  panes:
  - focus: 'true'
  start_directory: /Users/filipekiss/work/saraiva-magento
  window_name: Editor
- layout: bd2e,318x82,0,0[318x24,0,0,8,318x57,0,25{159x57,0,25[159x40,0,25,18,159x16,0,66,19],158x57,160,25,9}]
  options:
    automatic-rename: 'off'
  panes:
  - shell_command:
    - cd /Users/filipekiss/work/saraiva-docker
    - ctop -a
  - focus: 'true'
    shell_command:
    - cd /Users/filipekiss/work/saraiva-magento
    - git status
  - shell_command:
    - cd /Users/filipekiss/work/saraiva-magento/gulp
    - yarn gulp
  - shell_command:
    - cd /Users/filipekiss/work/saraiva-magento
    - vtop
  window_name: Utilities
