#!/usr/bin/env bash


function __ctags_main() {
    dir="`git rev-parse --show-toplevel`"
    [[ -e "${dir}/.notags" ]] && return 0
    trap 'rm -f "$dir/$$.tags"' EXIT
    git ls-files | ctags -L - -f"$dir/$$.tags" > /dev/null 2>&1
    mv "$dir/$$.tags" "$dir/tags"
}

export __ctags_main


nohup bash -c __ctags_main > /dev/null 2>&1 &
exit 0
