#!/usr/bin/env bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
source "${DIR}/utils/utils"

[[ ${IS_OSX} == ${NO} ]] && e_error "Oops.This is not OS X." && exit 1;

brew update
brew bundle --file=~/.dotfiles/homebrew/Brewfile
brew cleanup
brew doctor
