#!/usr/bin/env bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi
source "${DIR}/utils/utils"

#before stowing, let's create the folders so we don't end up with useless stuff in our repo that we must ignore

STOW_FOLDERS=$(find config/* -mindepth 1 -maxdepth 1 -type d)

e_header "Creating config folders at $HOME"
for FOLDER in $STOW_FOLDERS; do
  FOLDER=$(basename $FOLDER)
  [[ -d "${HOME}/${FOLDER}" || -L "${HOME}/${FOLDER}" ]] && e_info "${FOLDER} already exists. Skipping..." && continue
  mkdir -p "${HOME}/${FOLDER}" && e_success "${FOLDER} created"
done;
e_info "Linking files"
stow --ignore ".DS_Store" --target="$HOME" --dir="$HOME/.dotfiles/config" \
  bin \
  git \
  dig \
  atom \
  zsh
