#!/bin/sh
set -e
function main() {
    dir="`git rev-parse --git-dir`"
    trap 'rm -f "$dir/$$.tags"' EXIT
    git ls-files | ctags -L - -f"$dir/$$.tags" > /dev/null 2>&1
    mv "$dir/$$.tags" "$dir/tags"
}


main &
